
version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "
      python simple_vpn/manage.py runserver 0.0.0.0:8000 --noreload
      "