# Generated by Django 5.0.1 on 2024-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='name_slug',
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
